### ISSUE TITLE
Use polyfill.io once symbols are fixed

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy#1]
See: https://github.com/Financial-Times/polyfill-service/issues/1058

**Comment by satazor** [comment]
The issue has been fixed. We are awaiting for the `v3.17` release, see: https://github.com/Financial-Times/polyfill-service/milestone/32

**Comment by antoniocapelo** [comment]
This issue was moved to moxystudio/react-with-moxy-2#2
