### ISSUE TITLE
Ideas for the future of this boilerplate

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#10]
_From @satazor on March 11, 2017 23:19_

## Upgrades

One of the problems with boilerplates is how developers upgrade. What most boilerplates suggest is to look into the changelog and upgrade things carefully. While this works, it's a hard and cumbersome process. It ultimately discourages upgrading due to the time-consuming and error-prone tasks that developers must undergo.
One alternative is to fork the boilerplate and pull changes from git. This is what we have been doing but it also has its disadvantages: boilerplate history is mixed with the project history & sometimes it's not possible e.g.: when the client-side project is mixed with other projects on the same repository.

To alleviate this, we could create a `yeoman` generator. By using `yo`, developers would be prompted on modified/deleted files when running the generator on an old project:

![overwrite](https://cdn-images-1.medium.com/max/800/0*Yo4Mgt416vahgC5l.)

Additionally, we would benefit from offering `variations` of this boilerplate thanks to `yo` facilitating this. Developers would be prompted when creating their projects so that they could tweak stuff, e.g.:

- Do you want to use redux?
- Do you want css modules?
- Do you want cssnext?
- ..

Of course this would introduce complexity and we need to measure if it's worth it.

## Tooling & eject

All the tooling is currently part of project. This gives full flexibility to developers but it adds a lot of dependencies, scripts and configuration that are unlikely to change for simple/medium projects. 

`creat-react-app` solves this by abstracting all this tooling into a dev-dependency. I like it, since it looks simple for end-developers and that's one of the main reasons why it is so successful. And, when you need to tweak some aspect of the tooling such as webpack config or babel config, you can `eject`. This will remove the `dev-dependency` and copy ALL the tooling to your project.

I would like to do something similar but in a more interesting way. What if we could cherry pick what we could eject? For instance, what if I only need to tweak the `dev-server`? It would be cool if I could create `bin/dev-server` and the tooling would automatically detect this file and use it instead of the default one. Same applies for babel & webpack config, scripts in `bin/`, etc.

Thoughts?

_Copied from original issue: moxystudio/react-with-moxy#33_

**Comment by antoniocapelo** [comment]
_From @satazor on March 12, 2017 9:17_

See https://medium.com/@kitze/configure-create-react-app-without-ejecting-d8450e96196a#.im8l4bhky

**Comment by satazor** [comment]
Closing in favor of https://github.com/moxystudio/react-with-moxy-scripts
