### ISSUE TITLE
Link prefetching configuration

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#12]
_From @vasco-santos on February 27, 2017 15:14_

It would be interesting to consider a different mechanism for the prefetch, as a consequence of it being stuck to the `src/pages` path.

A recommendation would be to rename the config to `asyncPathsToPrefetch`, which would be available for all the`src` subdirectories.

_Copied from original issue: moxystudio/react-with-moxy#26_

**Comment by satazor** [comment]
This is no longer necessary with #30. All non-main assets are being prefetched by default. You may also filter out explicitly what should NOT be prefetched in your `.index.html.js` file.
