### ISSUE TITLE
Deal with rendering issues

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#13]
_From @satazor on February 19, 2017 12:40_

At the moment, if `render` or similar functions throw an error the following happens:

- On the server-side, the `internal-error` is rendered, which is ok!
- On the client-side, all falls apart with a blank page.

See: https://github.com/facebook/react/issues/2461

_Copied from original issue: moxystudio/react-with-moxy#20_

**Comment by satazor** [comment]
Now that #30 added react v16 we now have [componentDidCatch](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html). We should now re-evaluate this.
