### ISSUE TITLE
Consider doing gzip ahead of time

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#19]
_From @satazor on February 12, 2017 13:23_

Basically we could generate `.gz` files for all files currently being compressed on the fly and use [connect-gzip-static](https://github.com/code42day/connect-gzip-static) to server those.

In case if we are using `nginx` to serve these static files, there's http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html?&_ga=1.84404953.1168756284.1486903519#gzip_static

_Copied from original issue: moxystudio/react-with-moxy#11_

**Comment by satazor** [comment]
See: https://github.com/webpack-contrib/compression-webpack-plugin
