### ISSUE TITLE
Use polyfill.io once symbols are fixed

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#2]
_From @satazor on February 8, 2017 12:42_

See: https://github.com/Financial-Times/polyfill-service/issues/1058

_Copied from original issue: moxystudio/react-with-moxy#1_

**Comment by antoniocapelo** [comment]
_From @satazor on February 27, 2017 3:12_

The issue has been fixed. We are awaiting for the `v3.17` release, see: https://github.com/Financial-Times/polyfill-service/milestone/32

**Comment by satazor** [comment]
With #30 this became secondary because only the polyfills necessary from our targets are delivered which is a great improvement!

**Comment by satazor** [comment]
We now just need a way to get which polyfills the `babel-preset-env` uses and correlated them their polyfill.io counter-parts.

@jakechampion do you have news on this?

**Comment by satazor** [comment]
Closing this for now.
