### ISSUE TITLE
Generate a css file for each split point

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy#2]
Due to a limitation in [extract-text-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/332) we are generating a single app css file. Ideally we would have a css file per webpack split point (per bundle). We must wait for this issue to be solved.

Alternatively we can explore other solutions such as https://github.com/kriasoft/isomorphic-style-loader

**Comment by satazor** [comment]
Investigate https://github.com/faceyspacey/extract-css-chunks-webpack-plugin

**Comment by antoniocapelo** [comment]
This issue was moved to moxystudio/react-with-moxy-2#3
