### ISSUE TITLE
Give user suggestion to use another port when default one is selected

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#25]
What's described in the title, basically warn the user that the default port is selected and make him opt in to use the next available port to start the dev server.

**Comment by satazor** [comment]
@antoniocapelo Don't you think this could be done automatically for the `dev-server`?

**Comment by satazor** [comment]
@antoniocapelo I think that the ideal solution is something like `cra` is doing:

<img width="734" alt="screen shot 2017-03-12 at 15 51 49" src="https://cloud.githubusercontent.com/assets/1017236/23833332/dbddeecc-073b-11e7-9ec0-bfbbe477e24b.png">

..but it would require one more dep and some more code. If we decided to put our tooling in its own repo (#33), then we can implement it there.

For now it looks like this:

<img width="584" alt="screen shot 2017-03-12 at 15 53 49" src="https://cloud.githubusercontent.com/assets/1017236/23833358/1e514ace-073c-11e7-8b4b-c5a8fab7aaa0.png">
