### ISSUE TITLE
Move built server-renderer out of web/build

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#25]
_From @satazor on February 19, 2017 22:6_

There's no reason for it to be there and might contain sensitive information if one is adding private stuff to `config` with `__SERVER__  ? 'some-private-key' : null`.

_Copied from original issue: moxystudio/react-with-moxy#21_

**Comment by satazor** [comment]
With #30 this is no longer an issue since secret config is no longer exposed.
