### ISSUE TITLE
Generate a css file for each split point

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#3]
_From @satazor on February 8, 2017 15:32_

Due to a limitation in [extract-text-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/332) we are generating a single app css file. Ideally we would have a css file per webpack split point (per bundle). We must wait for this issue to be solved.

Alternatively we can explore other solutions such as https://github.com/kriasoft/isomorphic-style-loader

_Copied from original issue: moxystudio/react-with-moxy#2_

**Comment by antoniocapelo** [comment]
_From @satazor on May 3, 2017 15:30_

Investigate https://github.com/faceyspacey/extract-css-chunks-webpack-plugin

**Comment by satazor** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin
