### ISSUE TITLE
Speeding up linting in precommit hook

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy#30]
For large projects, linting all files can take a good amount of time. We can speed up things if we could only target added/edited files using `git status`.

Though, running `npm run lint` should still target the whole project. Perhaps we could add a `flag` like `--only-changed` or something similar to change the behavior.

**Comment by marcooliveira** [comment]
Relevant for this:

https://github.com/nrn/eslint-staged
https://www.npmjs.com/package/eslint-git-changes

**Comment by satazor** [comment]
See also https://github.com/okonet/lint-staged

Looks like it supports both `eslint` and `stylelint`.

**Comment by antoniocapelo** [comment]
This issue was moved to moxystudio/react-with-moxy-2#11
