### ISSUE TITLE
Re-use tab instead of opening a new tab

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy#32]
It would be nice if we could re-use the same tab instead of opening a new one everytime we start the dev server. CRA does it in an hacky way. Perhaps we could create a module for this?

**Comment by andrefgneves** [comment]
Should we consider an option to not open a browser at all?

**Comment by satazor** [comment]
@andrefgneves Yep we could.

**Comment by satazor** [comment]
For reference: https://github.com/facebookincubator/create-react-app/blob/19e0bb1881e24fb1ee3fe421413d4d87e67f68dd/packages/react-dev-utils/openBrowser.js#L64

**Comment by diogoribeiro23** [comment]
@satazor I would like to pick this up! Could you specify what you intend for this enhancement?
I think it's only possible to re-use an existing tab on MacOS. I could also add the option to not open a browser at all.
Thanks!

**Comment by satazor** [comment]
Hello @diogoribeiro23. That's cool.

So, the main task is to do a best-effort to reuse the browser tab if already open. According to `create-react-app`, that is only possible in MacOSx & Chrome. Later we might find additional strategies to do the same on other OSs/browsers and add support for them. My suggestion is to either:

- Add a openBrowser.js to this repository that tries to mimic what `create-react-app` does.
- Create an OSS package, that basically is like [opn](https://npms.io/search?q=opn) but with the option to re-use the tab.

I prefer the later, though it's a bit more complex but also challenging :)
We would do that ourselves sooner or later anyway, that is, if you opt for the first option we would extract to its own module in the future.

If you have any questions, I can answer them.

**Comment by satazor** [comment]
Regarding the option to not open the browser at all, I would do it in a separate PR. But supporting re-using the tab has more priority for us.

**Comment by diogoribeiro23** [comment]
@satazor I was thinking about integrating the OSS package that already provides `create-react-app` with the openBrowser.js, which is `react-dev-utils`.

Do you think it makes sense to create an OSS package just with the openBrowser.js and the associated files?

**Comment by satazor** [comment]
@diogoribeiro23 I didn't know that they had that functionality in a separate package. In that case, you may use it!

Nice catch.

**Comment by satazor** [comment]
Just a note: you don’t need to implement any tests because there aren’t any for the tooling part of this repo. Later on, we will migrate all the tooling scripts to a separate package that will be called react-with-moxy-scripts which will have comprehensive tests.

**Comment by diogoribeiro23** [comment]
Hey again @satazor! I came into a problem with the openBrowser functionality since it doesn't receive any parameters for the options of the opn method that is called within(e.g. wait).
I could:

- like you said, add the openBrowser.js to the utils folder in the scripts folder and change it as we want;

- Submit a PR to the `create-react-app` adding that feature for, posteriorly, use in the `react-with-moxy`, which would take a bit more time since they have to accept it and all.

What do you think?

**Comment by diogoribeiro23** [comment]
Or maybe you think it isn't a problem?

**Comment by satazor** [comment]
I think that it isn't a problem. The only option we use from `opn` is `wait: false`. It appears that `openBrowser` already doesn't wait for the browser process to end, so this isn't an issue.

**Comment by diogoribeiro23** [comment]
`openBrowser` doesn't wait for the browser process to end only on MacOS and if the env variable `BROWSER` is defined as `google chrome`, and on Windows if the env variable `BROWSER` is not defined. Anything else will use the `opn` with `wait: true` as it is it's default value.
So unless you want it to work only on your working environment, I think you will still need `the wait: false`, or am I wrong?

**Comment by satazor** [comment]
We still don't need it because they don't wait for the promise, they simply swallow any error: see https://github.com/facebookincubator/create-react-app/blob/d9799641268dfadffb625af68ce0a78895147728/packages/react-dev-utils/openBrowser.js#L100

Having that said, it's a non-issue.

**Comment by diogoribeiro23** [comment]
Well, that is what I was thinking but having the `wait: false` on your side confused me a bit. It means that you also didn't need to have it before, right?

I'll PR later at night.
Thanks!

**Comment by satazor** [comment]
Right. 👍
