### ISSUE TITLE
PWA ready

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy#8]
Investigate what needs to be done to make apps created with `react-with-moxy` a progressive web app.

**Comment by carsy** [comment]
some help here: https://developers.google.com/web/progressive-web-apps/

**Comment by antoniocapelo** [comment]
This issue was moved to moxystudio/react-with-moxy-2#21

**Comment by antoniocapelo** [comment]
This issue was moved to moxystudio/react-with-moxy-2#22
